const express = require('express');
const cors = require('cors');
const puppeteer = require('puppeteer');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());
app.use(express.static('.'));

const airports = [
    // USA
    { code: 'JFK', city: 'New York', country: 'USA', name: 'John F. Kennedy' },
    { code: 'LGA', city: 'New York', country: 'USA', name: 'LaGuardia' },
    { code: 'EWR', city: 'Newark', country: 'USA', name: 'Newark Liberty' },
    { code: 'LAX', city: 'Los Angeles', country: 'USA', name: 'Los Angeles Intl' },
    { code: 'ORD', city: 'Chicago', country: 'USA', name: "O'Hare" },
    { code: 'MDW', city: 'Chicago', country: 'USA', name: 'Midway' },
    { code: 'SFO', city: 'San Francisco', country: 'USA', name: 'San Francisco Intl' },
    { code: 'SEA', city: 'Seattle', country: 'USA', name: 'Seattle-Tacoma' },
    { code: 'MIA', city: 'Miami', country: 'USA', name: 'Miami Intl' },
    { code: 'FLL', city: 'Fort Lauderdale', country: 'USA', name: 'Fort Lauderdale' },
    { code: 'ATL', city: 'Atlanta', country: 'USA', name: 'Hartsfield-Jackson' },
    { code: 'DFW', city: 'Dallas', country: 'USA', name: 'Dallas/Fort Worth' },
    { code: 'DEN', city: 'Denver', country: 'USA', name: 'Denver Intl' },
    { code: 'BOS', city: 'Boston', country: 'USA', name: 'Logan' },
    { code: 'IAD', city: 'Washington', country: 'USA', name: 'Dulles' },
    { code: 'DCA', city: 'Washington', country: 'USA', name: 'Reagan National' },
    { code: 'PHX', city: 'Phoenix', country: 'USA', name: 'Sky Harbor' },
    { code: 'IAH', city: 'Houston', country: 'USA', name: 'George Bush Intercontinental' },
    { code: 'HOU', city: 'Houston', country: 'USA', name: 'Hobby' },
    { code: 'MSP', city: 'Minneapolis', country: 'USA', name: 'MSP' },
    { code: 'DTW', city: 'Detroit', country: 'USA', name: 'Metro Airport' },
    { code: 'PHL', city: 'Philadelphia', country: 'USA', name: 'Philadelphia Intl' },
    { code: 'SLC', city: 'Salt Lake City', country: 'USA', name: 'Salt Lake City Intl' },
    { code: 'SAN', city: 'San Diego', country: 'USA', name: 'San Diego Intl' },
    { code: 'TPA', city: 'Tampa', country: 'USA', name: 'Tampa Intl' },
    { code: 'PDX', city: 'Portland', country: 'USA', name: 'Portland Intl' },
    { code: 'HNL', city: 'Honolulu', country: 'USA', name: 'Daniel K. Inouye' },
    { code: 'ANC', city: 'Anchorage', country: 'USA', name: 'Ted Stevens' },
    { code: 'STL', city: 'St. Louis', country: 'USA', name: 'Lambert' },
    { code: 'BWI', city: 'Baltimore', country: 'USA', name: 'Baltimore/Washington' },
    { code: 'CLT', city: 'Charlotte', country: 'USA', name: 'Charlotte Douglas' },
    { code: 'MCI', city: 'Kansas City', country: 'USA', name: 'Kansas City Intl' },
    { code: 'AUS', city: 'Austin', country: 'USA', name: 'Austin-Bergstrom' },
    { code: 'RDU', city: 'Raleigh', country: 'USA', name: 'Raleigh-Durham' },
    { code: 'SMF', city: 'Sacramento', country: 'USA', name: 'Sacramento' },
    { code: 'SJC', city: 'San Jose', country: 'USA', name: 'San Jose' },
    { code: 'OAK', city: 'Oakland', country: 'USA', name: 'Oakland' },
    { code: 'MSY', city: 'New Orleans', country: 'USA', name: 'Louis Armstrong' },
    { code: 'NASH', city: 'Nashville', country: 'USA', name: 'Nashville' },
    { code: 'IND', city: 'Indianapolis', country: 'USA', name: 'Indianapolis' },
    { code: 'CMH', city: 'Columbus', country: 'USA', name: 'John Glenn Columbus' },
    { code: 'CLE', city: 'Cleveland', country: 'USA', name: 'Cleveland Hopkins' },
    { code: 'PIT', city: 'Pittsburgh', country: 'USA', name: 'Pittsburgh Intl' },
    { code: 'CVG', city: 'Cincinnati', country: 'USA', name: 'Cincinnati/Northern Kentucky' },
    { code: 'MKE', city: 'Milwaukee', country: 'USA', name: 'Mitchell' },
    { code: 'SAT', city: 'San Antonio', country: 'USA', name: 'San Antonio Intl' },
    { code: 'JAX', city: 'Jacksonville', country: 'USA', name: 'Jacksonville' },
    { code: 'RNO', city: 'Reno', country: 'USA', name: 'Reno-Tahoe' },
    { code: 'BOI', city: 'Boise', country: 'USA', name: 'Boise' },
    { code: 'ABQ', city: 'Albuquerque', country: 'USA', name: 'Albuquerque Sunport' },
    { code: 'OMA', city: 'Omaha', country: 'USA', name: 'Eppley Airfield' },
    { code: 'TUL', city: 'Tulsa', country: 'USA', name: 'Tulsa' },
    { code: 'OKC', city: 'Oklahoma City', country: 'USA', name: 'Will Rogers' },
    { code: 'DSM', city: 'Des Moines', country: 'USA', name: 'Des Moines' },
    { code: 'RIC', city: 'Richmond', country: 'USA', name: 'Richmond' },
    { code: 'ORF', city: 'Norfolk', country: 'USA', name: 'Norfolk Intl' },
    { code: 'BUF', city: 'Buffalo', country: 'USA', name: 'Buffalo Niagara' },
    { code: 'ROC', city: 'Rochester', country: 'USA', name: 'Rochester' },
    { code: 'SYR', city: 'Syracuse', country: 'USA', name: 'Syracuse Hancock' },
    { code: 'ALB', city: 'Albany', country: 'USA', name: 'Albany Intl' },
    { code: 'BDL', city: 'Hartford', country: 'USA', name: 'Bradley Intl' },
    { code: 'PVD', city: 'Providence', country: 'USA', name: 'T.F. Green' },
    // Canada
    { code: 'YYZ', city: 'Toronto', country: 'Canada', name: 'Pearson' },
    { code: 'YVR', city: 'Vancouver', country: 'Canada', name: 'Vancouver Intl' },
    { code: 'YUL', city: 'Montreal', country: 'Canada', name: 'Trudeau' },
    { code: 'YOW', city: 'Ottawa', country: 'Canada', name: 'Ottawa' },
    { code: 'YYC', city: 'Calgary', country: 'Canada', name: 'Calgary' },
    { code: 'YEG', city: 'Edmonton', country: 'Canada', name: 'Edmonton' },
    { code: 'YWG', city: 'Winnipeg', country: 'Canada', name: 'Winnipeg' },
    { code: 'YHZ', city: 'Halifax', country: 'Canada', name: 'Halifax Stanfield' },
    { code: 'YYT', city: 'St. John\'s', country: 'Canada', name: 'St. John\'s' },
    { code: 'YQR', city: 'Regina', country: 'Canada', name: 'Regina' },
    { code: 'YXE', city: 'Saskatoon', country: 'Canada', name: 'Saskatoon' },
    // Mexico
    { code: 'MEX', city: 'Mexico City', country: 'Mexico', name: 'Benito Juarez' },
    { code: 'CUN', city: 'Cancun', country: 'Mexico', name: 'Cancun Intl' },
    { code: 'GDL', city: 'Guadalajara', country: 'Mexico', name: 'Miguel Hidalgo' },
    { code: 'MTY', city: 'Monterrey', country: 'Mexico', name: 'Monterrey' },
    { code: 'PVR', city: 'Puerto Vallarta', country: 'Mexico', name: 'Puerto Vallarta' },
    { code: 'SJD', city: 'San Jose del Cabo', country: 'Mexico', name: 'Los Cabos' },
    { code: 'TIJ', city: 'Tijuana', country: 'Mexico', name: 'Tijuana' },
    { code: 'HMO', city: 'Hermosillo', country: 'Mexico', name: 'Hermosillo' },
    { code: 'CUU', city: 'Chihuahua', country: 'Mexico', name: 'Chihuahua' },
    { code: 'MID', city: 'Merida', country: 'Mexico', name: 'Merida' },
    { code: 'OAX', city: 'Oaxaca', country: 'Mexico', name: 'Oaxaca' },
    { code: 'PBC', city: 'Puebla', country: 'Mexico', name: 'Puebla' },
    // Central America
    { code: 'PTY', city: 'Panama City', country: 'Panama', name: 'Tocumen' },
    { code: 'SJO', city: 'San Jose', country: 'Costa Rica', name: 'Juan Santamaria' },
    { code: 'LIR', city: 'Liberia', country: 'Costa Rica', name: 'Daniel Oduber' },
    { code: 'GUA', city: 'Guatemala City', country: 'Guatemala', name: 'La Aurora' },
    { code: 'SAL', city: 'San Salvador', country: 'El Salvador', name: 'Monseñor Óscar Arnulfo Romero' },
    { code: 'TGU', city: 'Tegucigalpa', country: 'Honduras', name: 'Toncontin' },
    { code: 'MGA', city: 'Managua', country: 'Nicaragua', name: 'Augusto Sandino' },
    { code: 'SAP', city: 'San Pedro Sula', country: 'Honduras', name: 'Ramón Villeda Morales' },
    // Caribbean
    { code: 'SJU', city: 'San Juan', country: 'Puerto Rico', name: 'Luis Munoz Marin' },
    { code: 'NAS', city: 'Nassau', country: 'Bahamas', name: 'Nassau' },
    { code: 'MBJ', city: 'Montego Bay', country: 'Jamaica', name: 'Sangster' },
    { code: 'KIN', city: 'Kingston', country: 'Jamaica', name: 'Norman Manley' },
    { code: 'PUJ', city: 'Punta Cana', country: 'Dominican Republic', name: 'Punta Cana' },
    { code: 'SDQ', city: 'Santo Domingo', country: 'Dominican Republic', name: 'Las Americas' },
    { code: 'HAV', city: 'Havana', country: 'Cuba', name: 'José Martí' },
    { code: 'POS', city: 'Port of Spain', country: 'Trinidad and Tobago', name: 'Piarco' },
    { code: 'BGI', city: 'Bridgetown', country: 'Barbados', name: 'Grantley Adams' },
    { code: 'SJU', city: 'San Juan', country: 'Puerto Rico', name: 'Luis Munoz Marin' },
    { code: 'PSE', city: 'Ponce', country: 'Puerto Rico', name: 'Mercedita' },
    // South America
    { code: 'GRU', city: 'Sao Paulo', country: 'Brazil', name: 'Guarulhos' },
    { code: 'CGH', city: 'Sao Paulo', country: 'Brazil', name: 'Congonhas' },
    { code: 'GIG', city: 'Rio de Janeiro', country: 'Brazil', name: 'Galeao' },
    { code: 'SDU', city: 'Rio de Janeiro', country: 'Brazil', name: 'Santos Dumont' },
    { code: 'BSB', city: 'Brasilia', country: 'Brazil', name: 'Presidente Juscelino Kubitschek' },
    { code: 'CNF', city: 'Belo Horizonte', country: 'Brazil', name: 'Confins' },
    { code: 'SSA', city: 'Salvador', country: 'Brazil', name: 'Deputado Luís Eduardo Magalhães' },
    { code: 'REC', city: 'Recife', country: 'Brazil', name: 'Guararapes' },
    { code: 'FOR', city: 'Fortaleza', country: 'Brazil', name: 'Pinto Martins' },
    { code: 'POA', city: 'Porto Alegre', country: 'Brazil', name: 'Salgado Filho' },
    { code: 'CWB', city: 'Curitiba', country: 'Brazil', name: 'Afonso Pena' },
    { code: 'NAT', city: 'Natal', country: 'Brazil', name: 'Augusto Severo' },
    { code: 'VCP', city: 'Campinas', country: 'Brazil', name: 'Viracopos' },
    { code: 'EZE', city: 'Buenos Aires', country: 'Argentina', name: 'Ezeiza' },
    { code: 'AEP', city: 'Buenos Aires', country: 'Argentina', name: 'Aeroparque' },
    { code: 'COR', city: 'Cordoba', country: 'Argentina', name: 'Ingeniero Ambrosio Taravella' },
    { code: 'SCL', city: 'Santiago', country: 'Chile', name: 'Arturo Merino Benitez' },
    { code: 'LIM', city: 'Lima', country: 'Peru', name: 'Jorge Chavez' },
    { code: 'BOG', city: 'Bogota', country: 'Colombia', name: 'El Dorado' },
    { code: 'MDE', city: 'Medellin', country: 'Colombia', name: 'Jose Maria Cordova' },
    { code: 'CLO', city: 'Cali', country: 'Colombia', name: 'Alfonso Bonilla Aragon' },
    { code: 'UIO', city: 'Quito', country: 'Ecuador', name: 'Mariscal Sucre' },
    { code: 'GYE', city: 'Guayaquil', country: 'Ecuador', name: 'Jose Joaquin de Olmedo' },
    { code: 'CCS', city: 'Caracas', country: 'Venezuela', name: 'Simon Bolivar' },
    { code: 'MVD', city: 'Montevideo', country: 'Uruguay', name: 'Carrasco' },
    { code: 'ASU', city: 'Asuncion', country: 'Paraguay', name: 'Silvio Pettirossi' },
    { code: 'LPB', city: 'La Paz', country: 'Bolivia', name: 'El Alto' },
    { code: 'VVI', city: 'Santa Cruz', country: 'Bolivia', name: 'Viru Viru' },
    { code: 'PNH', city: 'Phnom Penh', country: 'Cambodia', name: 'Phnom Penh Intl' },
    // UK & Ireland
    { code: 'LHR', city: 'London', country: 'UK', name: 'Heathrow' },
    { code: 'LGW', city: 'London', country: 'UK', name: 'Gatwick' },
    { code: 'STN', city: 'London', country: 'UK', name: 'Stansted' },
    { code: 'LTN', city: 'London', country: 'UK', name: 'Luton' },
    { code: 'LCY', city: 'London', country: 'UK', name: 'London City' },
    { code: 'MAN', city: 'Manchester', country: 'UK', name: 'Manchester' },
    { code: 'BHX', city: 'Birmingham', country: 'UK', name: 'Birmingham' },
    { code: 'EDI', city: 'Edinburgh', country: 'UK', name: 'Edinburgh' },
    { code: 'GLA', city: 'Glasgow', country: 'UK', name: 'Glasgow' },
    { code: 'BRS', city: 'Bristol', country: 'UK', name: 'Bristol' },
    { code: 'LPL', city: 'Liverpool', country: 'UK', name: 'Liverpool John Lennon' },
    { code: 'NCL', city: 'Newcastle', country: 'UK', name: 'Newcastle' },
    { code: 'LEEDS', city: 'Leeds', country: 'UK', name: 'Leeds Bradford' },
    { code: 'DUB', city: 'Dublin', country: 'Ireland', name: 'Dublin' },
    { code: 'SNN', city: 'Shannon', country: 'Ireland', name: 'Shannon' },
    { code: 'CORK', city: 'Cork', country: 'Ireland', name: 'Cork' },
    // France
    { code: 'CDG', city: 'Paris', country: 'France', name: 'Charles de Gaulle' },
    { code: 'ORY', city: 'Paris', country: 'France', name: 'Orly' },
    { code: 'NCE', city: 'Nice', country: 'France', name: 'Cote d\'Azur' },
    { code: 'LYS', city: 'Lyon', country: 'France', name: 'Lyon-Saint Exupery' },
    { code: 'MRS', city: 'Marseille', country: 'France', name: 'Marseille Provence' },
    { code: 'TLS', city: 'Toulouse', country: 'France', name: 'Toulouse-Blagnac' },
    { code: 'BOD', city: 'Bordeaux', country: 'France', name: 'Bordeaux-Merignac' },
    { code: 'NTE', city: 'Nantes', country: 'France', name: 'Nantes Atlantique' },
    { code: 'SXB', city: 'Strasbourg', country: 'France', name: 'Strasbourg' },
    { code: 'MPL', city: 'Montpellier', country: 'France', name: 'Montpellier-Méditerranée' },
    // Germany
    { code: 'FRA', city: 'Frankfurt', country: 'Germany', name: 'Frankfurt am Main' },
    { code: 'MUC', city: 'Munich', country: 'Germany', name: 'Munich' },
    { code: 'BER', city: 'Berlin', country: 'Germany', name: 'Brandenburg' },
    { code: 'DUS', city: 'Dusseldorf', country: 'Germany', name: 'Dusseldorf' },
    { code: 'HAM', city: 'Hamburg', country: 'Germany', name: 'Hamburg' },
    { code: 'CGN', city: 'Cologne', country: 'Germany', name: 'Cologne Bonn' },
    { code: 'STR', city: 'Stuttgart', country: 'Germany', name: 'Stuttgart' },
    { code: 'HAJ', city: 'Hannover', country: 'Germany', name: 'Hannover' },
    { code: 'NUE', city: 'Nuremberg', country: 'Germany', name: 'Nuremberg' },
    { code: 'LEJ', city: 'Leipzig', country: 'Germany', name: 'Leipzig/Halle' },
    // Italy
    { code: 'FCO', city: 'Rome', country: 'Italy', name: 'Fiumicino' },
    { code: 'CIA', city: 'Rome', country: 'Italy', name: 'Ciampino' },
    { code: 'MXP', city: 'Milan', country: 'Italy', name: 'Malpensa' },
    { code: 'LIN', city: 'Milan', country: 'Italy', name: 'Linate' },
    { code: 'BGY', city: 'Milan', country: 'Italy', name: 'Bergamo' },
    { code: 'VCE', city: 'Venice', country: 'Italy', name: 'Marco Polo' },
    { code: 'TSR', city: 'Treviso', country: 'Italy', name: 'Treviso' },
    { code: 'NAP', city: 'Naples', country: 'Italy', name: 'Naples Intl' },
    { code: 'PSA', city: 'Pisa', country: 'Italy', name: 'Pisa' },
    { code: 'FLR', city: 'Florence', country: 'Italy', name: 'Peretola' },
    { code: 'BLQ', city: 'Bologna', country: 'Italy', name: 'Bologna' },
    { code: 'PMO', city: 'Palermo', country: 'Italy', name: 'Falcone-Borsellino' },
    { code: 'CTA', city: 'Catania', country: 'Italy', name: 'Catania' },
    { code: 'OLB', city: 'Olbia', country: 'Italy', name: 'Costa Smeralda' },
    { code: 'CAG', city: 'Cagliari', country: 'Italy', name: 'Cagliari' },
    // Spain
    { code: 'BCN', city: 'Barcelona', country: 'Spain', name: 'El Prat' },
    { code: 'MAD', city: 'Madrid', country: 'Spain', name: 'Barajas' },
    { code: 'AGP', city: 'Malaga', country: 'Spain', name: 'Costa del Sol' },
    { code: 'PMI', city: 'Palma de Mallorca', country: 'Spain', name: 'Son Sant Joan' },
    { code: 'TFS', city: 'Tenerife', country: 'Spain', name: 'Tenerife South' },
    { code: 'LPA', city: 'Gran Canaria', country: 'Spain', name: 'Gran Canaria' },
    { code: 'VLC', city: 'Valencia', country: 'Spain', name: 'Valencia' },
    { code: 'BIO', city: 'Bilbao', country: 'Spain', name: 'Bilbao' },
    { code: 'SVQ', city: 'Seville', country: 'Spain', name: 'San Pablo' },
    { code: 'GRX', city: 'Granada', country: 'Spain', name: 'Federico Garcia Lorca' },
    { code: 'ALC', city: 'Alicante', country: 'Spain', name: 'Alicante' },
    { code: 'ACE', city: 'Lanzarote', country: 'Spain', name: 'Lanzarote' },
    { code: 'FUE', city: 'Fuerteventura', country: 'Spain', name: 'Fuerteventura' },
    { code: 'IBZ', city: 'Ibiza', country: 'Spain', name: 'Ibiza' },
    { code: 'OPO', city: 'Porto', country: 'Portugal', name: 'Francisco Sa Carneiro' },
    { code: 'LIS', city: 'Lisbon', country: 'Portugal', name: 'Humberto Delgado' },
    { code: 'FAO', city: 'Faro', country: 'Portugal', name: 'Faro' },
    { code: 'FNC', city: 'Funchal', country: 'Portugal', name: 'Madeira' },
    // Netherlands & Belgium
    { code: 'AMS', city: 'Amsterdam', country: 'Netherlands', name: 'Schiphol' },
    { code: 'EIN', city: 'Eindhoven', country: 'Netherlands', name: 'Eindhoven' },
    { code: 'RTM', city: 'Rotterdam', country: 'Netherlands', name: 'Rotterdam The Hague' },
    { code: 'BRU', city: 'Brussels', country: 'Belgium', name: 'Brussels' },
    { code: 'CRL', city: 'Charleroi', country: 'Belgium', name: 'Brussels South Charleroi' },
    { code: 'LGG', city: 'Liege', country: 'Belgium', name: 'Liege' },
    // Switzerland & Austria
    { code: 'ZRH', city: 'Zurich', country: 'Switzerland', name: 'Zurich' },
    { code: 'GVA', city: 'Geneva', country: 'Switzerland', name: 'Geneva' },
    { code: 'BSL', city: 'Basel', country: 'Switzerland', name: 'EuroAirport' },
    { code: 'VIE', city: 'Vienna', country: 'Austria', name: 'Vienna Intl' },
    { code: 'SZG', city: 'Salzburg', country: 'Austria', name: 'Salzburg' },
    { code: 'INN', city: 'Innsbruck', country: 'Austria', name: 'Innsbruck' },
    { code: 'GRZ', city: 'Graz', country: 'Austria', name: 'Graz' },
    // Scandinavia
    { code: 'CPH', city: 'Copenhagen', country: 'Denmark', name: 'Copenhagen' },
    { code: 'ARN', city: 'Stockholm', country: 'Sweden', name: 'Arlanda' },
    { code: 'GOT', city: 'Gothenburg', country: 'Sweden', name: 'Landvetter' },
    { code: 'OSL', city: 'Oslo', country: 'Norway', name: 'Oslo Gardermoen' },
    { code: 'BGO', city: 'Bergen', country: 'Norway', name: 'Bergen' },
    { code: 'HEL', city: 'Helsinki', country: 'Finland', name: 'Vantaa' },
    { code: 'OUL', city: 'Oulu', country: 'Finland', name: 'Oulu' },
    { code: 'TMP', city: 'Tampere', country: 'Finland', name: 'Tampere-Pirkkala' },
    { code: 'KEF', city: 'Reykjavik', country: 'Iceland', name: 'Keflavik' },
    // Eastern Europe
    { code: 'WAW', city: 'Warsaw', country: 'Poland', name: 'Chopin' },
    { code: 'KRK', city: 'Krakow', country: 'Poland', name: 'John Paul II' },
    { code: 'GDN', city: 'Gdansk', country: 'Poland', name: 'Lech Walesa' },
    { code: 'WRO', city: 'Wroclaw', country: 'Poland', name: 'Wroclaw' },
    { code: 'PRG', city: 'Prague', country: 'Czech Republic', name: 'Vaclav Havel' },
    { code: 'BRQ', city: 'Brno', country: 'Czech Republic', name: 'Brno' },
    { code: 'BUD', city: 'Budapest', country: 'Hungary', name: 'Budapest Ferenc Liszt' },
    { code: 'OTP', city: 'Bucharest', country: 'Romania', name: 'Henri Coanda' },
    { code: 'CLJ', city: 'Cluj-Napoca', country: 'Romania', name: 'Avram Iancu' },
    { code: 'SOF', city: 'Sofia', country: 'Bulgaria', name: 'Sofia' },
    { code: 'VAR', city: 'Varna', country: 'Bulgaria', name: 'Varna' },
    { code: 'BEG', city: 'Belgrade', country: 'Serbia', name: 'Nikola Tesla' },
    { code: 'ZAG', city: 'Zagreb', country: 'Croatia', name: 'Franjo Tudjman' },
    { code: 'SPU', city: 'Split', country: 'Croatia', name: 'Split' },
    { code: 'DBV', city: 'Dubrovnik', country: 'Croatia', name: 'Dubrovnik' },
    { code: 'LJU', city: 'Ljubljana', country: 'Slovenia', name: 'Ljubljana' },
    { code: 'SKP', city: 'Skopje', country: 'North Macedonia', name: 'Alexander the Great' },
    { code: 'TGD', city: 'Podgorica', country: 'Montenegro', name: 'Podgorica' },
    { code: 'TIA', city: 'Tirana', country: 'Albania', name: 'Tirana Intl' },
    // Greece
    { code: 'ATH', city: 'Athens', country: 'Greece', name: 'Athens Intl' },
    { code: 'HER', city: 'Heraklion', country: 'Greece', name: 'Heraklion Intl' },
    { code: 'CHQ', city: 'Chania', country: 'Greece', name: 'Chania' },
    { code: 'RHO', city: 'Rhodes', country: 'Greece', name: 'Rhodes' },
    { code: 'CFU', city: 'Corfu', country: 'Greece', name: 'Corfu' },
    { code: 'SKG', city: 'Thessaloniki', country: 'Greece', name: 'Thessaloniki' },
    // Turkey
    { code: 'IST', city: 'Istanbul', country: 'Turkey', name: 'Istanbul Airport' },
    { code: 'SAW', city: 'Istanbul', country: 'Turkey', name: 'Sabiha Gokcen' },
    { code: 'ADB', city: 'Izmir', country: 'Turkey', name: 'Adnan Menderes' },
    { code: 'AYT', city: 'Antalya', country: 'Turkey', name: 'Antalya' },
    { code: 'ESB', city: 'Ankara', country: 'Turkey', name: 'Esenboga' },
    { code: 'DLM', city: 'Dalaman', country: 'Turkey', name: 'Dalaman' },
    { code: 'BOD', city: 'Bodrum', country: 'Turkey', name: 'Milas-Bodrum' },
    { code: 'GZT', city: 'Gaziantep', country: 'Turkey', name: 'Oguzeli' },
    { code: 'TZX', city: 'Trabzon', country: 'Turkey', name: 'Trabzon' },
    // Russia
    { code: 'SVO', city: 'Moscow', country: 'Russia', name: 'Sheremetyevo' },
    { code: 'DME', city: 'Moscow', country: 'Russia', name: 'Domodedovo' },
    { code: 'VKO', city: 'Moscow', country: 'Russia', name: 'Vnukovo' },
    { code: 'LED', city: 'St Petersburg', country: 'Russia', name: 'Pulkovo' },
    { code: 'OVB', city: 'Novosibirsk', country: 'Russia', name: 'Tolmachevo' },
    { code: 'KRR', city: 'Krasnodar', country: 'Russia', name: 'Pashkovsky' },
    { code: 'KZN', city: 'Kazan', country: 'Russia', name: 'Kazan' },
    { code: 'SVX', city: 'Yekaterinburg', country: 'Russia', name: 'Koltsovo' },
    { code: 'AER', city: 'Sochi', country: 'Russia', name: 'Sochi' },
    // Middle East
    { code: 'DXB', city: 'Dubai', country: 'UAE', name: 'Dubai Intl' },
    { code: 'AUH', city: 'Abu Dhabi', country: 'UAE', name: 'Abu Dhabi Intl' },
    { code: 'SHJ', city: 'Sharjah', country: 'UAE', name: 'Sharjah Intl' },
    { code: 'DOH', city: 'Doha', country: 'Qatar', name: 'Hamad Intl' },
    { code: 'RUH', city: 'Riyadh', country: 'Saudi Arabia', name: 'King Khalid' },
    { code: 'JED', city: 'Jeddah', country: 'Saudi Arabia', name: 'King Abdulaziz' },
    { code: 'MED', city: 'Medina', country: 'Saudi Arabia', name: 'Prince Mohammad bin Abdulaziz' },
    { code: 'BAH', city: 'Bahrain', country: 'Bahrain', name: 'Bahrain Intl' },
    { code: 'MCT', city: 'Muscat', country: 'Oman', name: 'Muscat Intl' },
    { code: 'KWI', city: 'Kuwait City', country: 'Kuwait', name: 'Kuwait Intl' },
    { code: 'AMM', city: 'Amman', country: 'Jordan', name: 'Queen Alia' },
    { code: 'TLV', city: 'Tel Aviv', country: 'Israel', name: 'Ben Gurion' },
    { code: 'CAI', city: 'Cairo', country: 'Egypt', name: 'Cairo Intl' },
    { code: 'HRG', city: 'Hurghada', country: 'Egypt', name: 'Hurghada Intl' },
    { code: 'SSH', city: 'Sharm El Sheikh', country: 'Egypt', name: 'Sharm El Sheikh Intl' },
    { code: 'TUN', city: 'Tunis', country: 'Tunisia', name: 'Tunis-Carthage' },
    { code: 'CMN', city: 'Casablanca', country: 'Morocco', name: 'Mohammed V' },
    { code: 'RAK', city: 'Marrakech', country: 'Morocco', name: 'Marrakech Menara' },
    { code: 'FEZ', city: 'Fez', country: 'Morocco', name: 'Fez-Sais' },
    // Africa
    { code: 'JNB', city: 'Johannesburg', country: 'South Africa', name: 'OR Tambo' },
    { code: 'CPT', city: 'Cape Town', country: 'South Africa', name: 'Cape Town Intl' },
    { code: 'DUR', city: 'Durban', country: 'South Africa', name: 'King Shaka' },
    { code: 'CMB', city: 'Colombo', country: 'Sri Lanka', name: 'Bandaranaike' },
    { code: 'NBO', city: 'Nairobi', country: 'Kenya', name: 'Jomo Kenyatta' },
    { code: 'MBA', city: 'Mombasa', country: 'Kenya', name: 'Moi Intl' },
    { code: 'ADD', city: 'Addis Ababa', country: 'Ethiopia', name: 'Bole' },
    { code: 'LOS', city: 'Lagos', country: 'Nigeria', name: 'Murtala Muhammed' },
    { code: 'ABV', city: 'Abuja', country: 'Nigeria', name: 'Nnamdi Azikiwe' },
    { code: 'ACC', city: 'Accra', country: 'Ghana', name: 'Kotoka' },
    { code: 'DSS', city: 'Dakar', country: 'Senegal', name: 'Blaise Diagne' },
    { code: 'CMR', city: 'Douala', country: 'Cameroon', name: 'Douala' },
    { code: 'DAR', city: 'Dar es Salaam', country: 'Tanzania', name: 'Julius Nyerere' },
    { code: 'ZNZ', city: 'Zanzibar', country: 'Tanzania', name: 'Abeid Karume' },
    { code: 'KRT', city: 'Khartoum', country: 'Sudan', name: 'Khartoum Intl' },
    { code: 'KGL', city: 'Kigali', country: 'Rwanda', name: 'Kigali Intl' },
    { code: 'EBB', city: 'Entebbe', country: 'Uganda', name: 'Entebbe Intl' },
    // Asia - Japan
    { code: 'NRT', city: 'Tokyo', country: 'Japan', name: 'Narita' },
    { code: 'HND', city: 'Tokyo', country: 'Japan', name: 'Haneda' },
    { code: 'KIX', city: 'Osaka', country: 'Japan', name: 'Kansai' },
    { code: 'ITM', city: 'Osaka', country: 'Japan', name: 'Itami' },
    { code: 'FUK', city: 'Fukuoka', country: 'Japan', name: 'Fukuoka' },
    { code: 'CTS', city: 'Sapporo', country: 'Japan', name: 'New Chitose' },
    { code: 'NGO', city: 'Nagoya', country: 'Japan', name: 'Chubu Centrair' },
    { code: 'OKA', city: 'Okinawa', country: 'Japan', name: 'Naha' },
    { code: 'KMJ', city: 'Kumamoto', country: 'Japan', name: 'Kumamoto' },
    { code: 'HIJ', city: 'Hiroshima', country: 'Japan', name: 'Hiroshima' },
    { code: 'MIY', city: 'Miyazaki', country: 'Japan', name: 'Miyazaki' },
    { code: 'OIT', city: 'Oita', country: 'Japan', name: 'Oita' },
    { code: 'ASJ', city: 'Amami', country: 'Japan', name: 'Amami' },
    { code: 'IKI', city: 'Iki', country: 'Japan', name: 'Iki' },
    { code: 'KOJ', city: 'Kagoshima', country: 'Japan', name: 'Kagoshima' },
    { code: 'MYJ', city: 'Matsuyama', country: 'Japan', name: 'Matsuyama' },
    { code: 'TAK', city: 'Takamatsu', country: 'Japan', name: 'Takamatsu' },
    { code: 'TKS', city: 'Tokushima', country: 'Japan', name: 'Tokushima' },
    { code: 'IWJ', city: 'Iwami', country: 'Japan', name: 'Iwami' },
    { code: 'ONJ', city: 'Odate-Noshiro', country: 'Japan', name: 'Odate-Noshiro' },
    { code: 'SYO', city: 'Shonai', country: 'Japan', name: 'Shonai' },
    { code: 'SDJ', city: 'Sendai', country: 'Japan', name: 'Sendai' },
    { code: 'KMQ', city: 'Komatsu', country: 'Japan', name: 'Komatsu' },
    { code: 'TOY', city: 'Toyama', country: 'Japan', name: 'Toyama' },
    { code: 'FSZ', city: 'Shizuoka', country: 'Japan', name: 'Shizuoka' },
    { code: 'MMY', city: 'Miyako', country: 'Japan', name: 'Miyako' },
    { code: 'ISG', city: 'Ishigaki', country: 'Japan', name: 'Ishigaki' },
    { code: 'MIS', city: 'Miyako', country: 'Japan', name: 'Miyako Jima' },
    { code: 'OKJ', city: 'Okayama', country: 'Japan', name: 'Okayama' },
    { code: 'IWK', city: 'Iwakuni', country: 'Japan', name: 'Iwakuni' },
    { code: 'KCJ', city: 'Kohnan', country: 'Japan', name: 'Kohnan' },
    // Asia - China
    { code: 'PEK', city: 'Beijing', country: 'China', name: 'Capital Intl' },
    { code: 'PKX', city: 'Beijing', country: 'China', name: 'Daxing' },
    { code: 'PVG', city: 'Shanghai', country: 'China', name: 'Pudong' },
    { code: 'SHA', city: 'Shanghai', country: 'China', name: 'Hongqiao' },
    { code: 'CAN', city: 'Guangzhou', country: 'China', name: 'Baiyun' },
    { code: 'SZX', city: 'Shenzhen', country: 'China', name: 'Bao\'an' },
    { code: 'CTU', city: 'Chengdu', country: 'China', name: 'Shuangliu' },
    { code: 'TFU', city: 'Chengdu', country: 'China', name: 'Tianfu' },
    { code: 'KMG', city: 'Kunming', country: 'China', name: 'Changshui' },
    { code: 'XIY', city: 'Xi\'an', country: 'China', name: 'Xianyang' },
    { code: 'HGH', city: 'Hangzhou', country: 'China', name: 'Xiaoshan' },
    { code: 'NKG', city: 'Nanjing', country: 'China', name: 'Nanjing Lukou' },
    { code: 'WUH', city: 'Wuhan', country: 'China', name: 'Tianhe' },
    { code: 'CKG', city: 'Chongqing', country: 'China', name: 'Jiangbei' },
    { code: 'TAO', city: 'Qingdao', country: 'China', name: 'Jiaodong' },
    { code: 'DLC', city: 'Dalian', country: 'China', name: 'Zhoushuizi' },
    { code: 'SHE', city: 'Shenyang', country: 'China', name: 'Taoxian' },
    { code: 'XMN', city: 'Xiamen', country: 'China', name: 'Xiamen Gaoqi' },
    { code: 'HAK', city: 'Haikou', country: 'China', name: 'Meilan' },
    { code: 'SYX', city: 'Sanya', country: 'China', name: 'Phoenix' },
    { code: 'CGO', city: 'Zhengzhou', country: 'China', name: 'Xinzheng' },
    { code: 'CSX', city: 'Changsha', country: 'China', name: 'Huanghua' },
    { code: 'TNA', city: 'Jinan', country: 'China', name: 'Yaoqiang' },
    { code: 'FOC', city: 'Fuzhou', country: 'China', name: 'Changle' },
    { code: 'KWE', city: 'Guiyang', country: 'China', name: 'Longdongbao' },
    { code: 'TYN', city: 'Taiyuan', country: 'China', name: 'Wusu' },
    { code: 'URC', city: 'Urumqi', country: 'China', name: 'Diwopu' },
    { code: 'HET', city: 'Hohhot', country: 'China', name: 'Baita' },
    { code: 'NNG', city: 'Nanning', country: 'China', name: 'Wuxu' },
    { code: 'LHW', city: 'Lanzhou', country: 'China', name: 'Zhongchuan' },
    { code: 'INC', city: 'Yinchuan', country: 'China', name: 'Heilan' },
    { code: 'XNN', city: 'Xining', country: 'China', name: 'Caojiabao' },
    { code: 'LXA', city: 'Lhasa', country: 'China', name: 'Gonggar' },
    { code: 'CZX', city: 'Changzhou', country: 'China', name: 'Changzhou' },
    { code: 'NTG', city: 'Nantong', country: 'China', name: 'Nantong' },
    { code: 'YNT', city: 'Yantai', country: 'China', name: 'Laishan' },
    { code: 'WEH', city: 'Weihai', country: 'China', name: 'Weihai' },
    { code: 'YNZ', city: 'Yancheng', country: 'China', name: 'Yancheng' },
    { code: 'HIA', city: 'Huai\'an', country: 'China', name: 'Huai\'an' },
    { code: 'XUZ', city: 'Xuzhou', country: 'China', name: 'Xuzhou' },
    { code: 'SWA', city: 'Shantou', country: 'China', name: 'Jieyang' },
    { code: 'ZUH', city: 'Zhuhai', country: 'China', name: 'Jinwan' },
    { code: 'MFM', city: 'Macau', country: 'Macau', name: 'Macau Intl' },
    // Asia - South Korea
    { code: 'ICN', city: 'Seoul', country: 'South Korea', name: 'Incheon' },
    { code: 'GMP', city: 'Seoul', country: 'South Korea', name: 'Gimpo' },
    { code: 'PUS', city: 'Busan', country: 'South Korea', name: 'Gimhae' },
    { code: 'CJU', city: 'Jeju', country: 'South Korea', name: 'Jeju Intl' },
    { code: 'TAE', city: 'Daegu', country: 'South Korea', name: 'Daegu' },
    { code: 'KPO', city: 'Pohang', country: 'South Korea', name: 'Pohang' },
    { code: 'RSU', city: 'Yeosu', country: 'South Korea', name: 'Yeosu' },
    { code: 'WJU', city: 'Wonju', country: 'South Korea', name: 'Wonju' },
    { code: 'YNY', city: 'Yangyang', country: 'South Korea', name: 'Yangyang' },
    // Asia - Hong Kong, Taiwan
    { code: 'HKG', city: 'Hong Kong', country: 'Hong Kong', name: 'Chek Lap Kok' },
    { code: 'TPE', city: 'Taipei', country: 'Taiwan', name: 'Taoyuan' },
    { code: 'TSA', city: 'Taipei', country: 'Taiwan', name: 'Songshan' },
    { code: 'KHH', city: 'Kaohsiung', country: 'Taiwan', name: 'Kaohsiung' },
    { code: 'RMQ', city: 'Taichung', country: 'Taiwan', name: 'Taichung' },
    { code: 'TNN', city: 'Tainan', country: 'Taiwan', name: 'Tainan' },
    { code: 'KNH', city: 'Kinmen', country: 'Taiwan', name: 'Kinmen' },
    { code: 'MZG', city: 'Makung', country: 'Taiwan', name: 'Makung' },
    // Asia - Southeast Asia
    { code: 'SIN', city: 'Singapore', country: 'Singapore', name: 'Changi' },
    { code: 'BKK', city: 'Bangkok', country: 'Thailand', name: 'Suvarnabhumi' },
    { code: 'DMK', city: 'Bangkok', country: 'Thailand', name: 'Don Mueang' },
    { code: 'CNX', city: 'Chiang Mai', country: 'Thailand', name: 'Chiang Mai Intl' },
    { code: 'HKT', city: 'Phuket', country: 'Thailand', name: 'Phuket Intl' },
    { code: 'USM', city: 'Koh Samui', country: 'Thailand', name: 'Koh Samui' },
    { code: 'KBV', city: 'Krabi', country: 'Thailand', name: 'Krabi' },
    { code: 'UTP', city: 'Pattaya', country: 'Thailand', name: 'U-Tapao' },
    { code: 'KUL', city: 'Kuala Lumpur', country: 'Malaysia', name: 'Kuala Lumpur Intl' },
    { code: 'PEN', city: 'Penang', country: 'Malaysia', name: 'Penang Intl' },
    { code: 'BKI', city: 'Kota Kinabalu', country: 'Malaysia', name: 'Kota Kinabalu Intl' },
    { code: 'KCH', city: 'Kuching', country: 'Malaysia', name: 'Kuching Intl' },
    { code: 'JHB', city: 'Johor Bahru', country: 'Malaysia', name: 'Senai' },
    { code: 'SZB', city: 'Subang', country: 'Malaysia', name: 'Sultan Abdul Aziz Shah' },
    { code: 'DPS', city: 'Bali', country: 'Indonesia', name: 'Ngurah Rai' },
    { code: 'CGK', city: 'Jakarta', country: 'Indonesia', name: 'Soekarno-Hatta' },
    { code: 'HLP', city: 'Jakarta', country: 'Indonesia', name: 'Halim Perdanakusuma' },
    { code: 'SUB', city: 'Surabaya', country: 'Indonesia', name: 'Juanda' },
    { code: 'MNL', city: 'Manila', country: 'Philippines', name: 'Ninoy Aquino' },
    { code: 'CEB', city: 'Cebu', country: 'Philippines', name: 'Mactan-Cebu Intl' },
    { code: 'CRK', city: 'Clark', country: 'Philippines', name: 'Clark Intl' },
    { code: 'DVO', city: 'Davao', country: 'Philippines', name: 'Francisco Bangoy' },
    { code: 'SGN', city: 'Ho Chi Minh City', country: 'Vietnam', name: 'Tan Son Nhat' },
    { code: 'HAN', city: 'Hanoi', country: 'Vietnam', name: 'Noi Bai' },
    { code: 'DAD', city: 'Da Nang', country: 'Vietnam', name: 'Da Nang Intl' },
    { code: 'CXR', city: 'Nha Trang', country: 'Vietnam', name: 'Cam Ranh' },
    { code: 'PQC', city: 'Phu Quoc', country: 'Vietnam', name: 'Phu Quoc Intl' },
    { code: 'VCL', city: 'Chu Lai', country: 'Vietnam', name: 'Chu Lai' },
    { code: 'VII', city: 'Vinh', country: 'Vietnam', name: 'Vinh' },
    { code: 'DLI', city: 'Da Lat', country: 'Vietnam', name: 'Lien Khuong' },
    { code: 'HUI', city: 'Hue', country: 'Vietnam', name: 'Phu Bai' },
    // Asia - South Asia
    { code: 'DEL', city: 'Delhi', country: 'India', name: 'Indira Gandhi' },
    { code: 'BOM', city: 'Mumbai', country: 'India', name: 'Chhatrapati Shivaji' },
    { code: 'BLR', city: 'Bangalore', country: 'India', name: 'Kempegowda' },
    { code: 'MAA', city: 'Chennai', country: 'India', name: 'Chennai Intl' },
    { code: 'HYD', city: 'Hyderabad', country: 'India', name: 'Rajiv Gandhi' },
    { code: 'CCU', city: 'Kolkata', country: 'India', name: 'Netaji Subhas Chandra Bose' },
    { code: 'COK', city: 'Kochi', country: 'India', name: 'Cochin Intl' },
    { code: 'GOI', city: 'Goa', country: 'India', name: 'Dabolim' },
    { code: 'PNQ', city: 'Pune', country: 'India', name: 'Pune Intl' },
    { code: 'AMD', city: 'Ahmedabad', country: 'India', name: 'Sardar Vallabhbhai Patel' },
    { code: 'JAI', city: 'Jaipur', country: 'India', name: 'Jaipur Intl' },
    { code: 'LKO', city: 'Lucknow', country: 'India', name: 'Chaudhary Charan Singh' },
    { code: 'PAT', city: 'Patna', country: 'India', name: 'Jay Prakash Narayan' },
    { code: 'BHO', city: 'Bhopal', country: 'India', name: 'Raja Bhoj' },
    { code: 'Indore', city: 'Indore', country: 'India', name: 'Devi Ahilyabai Holkar' },
    { code: 'NAG', city: 'Nagpur', country: 'India', name: 'Dr. Babasaheb Ambedkar' },
    { code: 'TRV', city: 'Thiruvananthapuram', country: 'India', name: 'Trivandrum Intl' },
    { code: 'IXM', city: 'Madurai', country: 'India', name: 'Madurai' },
    { code: 'TRZ', city: 'Tiruchirappalli', country: 'India', name: 'Tiruchirappalli' },
    { code: 'IXR', city: 'Ranchi', country: 'India', name: 'Ranchi' },
    { code: 'IXB', city: 'Bagdogra', country: 'India', name: 'Bagdogra' },
    { code: 'GAU', city: 'Guwahati', country: 'India', name: 'Lokpriya Gopinath Bordoloi' },
    { code: 'IMF', city: 'Imphal', country: 'India', name: 'Imphal' },
    { code: 'SHL', city: 'Shillong', country: 'India', name: 'Shillong' },
    { code: 'DIB', city: 'Dibrugarh', country: 'India', name: 'Mohanbari' },
    { code: 'JMU', city: 'Jamshedpur', country: 'India', name: 'Sonari' },
    { code: 'RPR', city: 'Raipur', country: 'India', name: 'Swami Vivekananda' },
    { code: 'JDH', city: 'Jodhpur', country: 'India', name: 'Jodhpur' },
    { code: 'UDR', city: 'Udaipur', country: 'India', name: 'Maharana Pratap' },
    { code: 'IDR', city: 'Indore', country: 'India', name: 'Devi Ahilyabai Holkar' },
    { code: 'CJB', city: 'Coimbatore', country: 'India', name: 'Coimbatore Intl' },
    { code: 'VGA', city: 'Vijayawada', country: 'India', name: 'Gannavaram' },
    { code: 'VTZ', city: 'Visakhapatnam', country: 'India', name: 'Visakhapatnam' },
    { code: 'RJA', city: 'Rajahmundry', country: 'India', name: 'Rajahmundry' },
    { code: 'BBI', city: 'Bhubaneswar', country: 'India', name: 'Biju Patnaik' },
    { code: 'IXA', city: 'Agartala', country: 'India', name: 'Maharaja Bir Bikram' },
    { code: 'AJL', city: 'Aizawl', country: 'India', name: 'Lengpui' },
    { code: 'DMU', city: 'Dimapur', country: 'India', name: 'Dimapur' },
    { code: 'IXI', city: 'Lilabari', country: 'India', name: 'Lilabari' },
    { code: 'TEZ', city: 'Tezpur', country: 'India', name: 'Salonibari' },
    { code: 'BKB', city: 'Bikaner', country: 'India', name: 'Bikaner' },
    { code: 'JSA', city: 'Jaisalmer', country: 'India', name: 'Jaisalmer' },
    { code: 'KUU', city: 'Kullu', country: 'India', name: 'Bhuntar' },
    { code: 'SLV', city: 'Shimla', country: 'India', name: 'Shimla' },
    { code: 'DHM', city: 'Kangra', country: 'India', name: 'Gaggal' },
    { code: 'IXJ', city: 'Jammu', country: 'India', name: 'Jammu' },
    { code: 'SXR', city: 'Srinagar', country: 'India', name: 'Sheikh ul-Alam' },
    { code: 'IXL', city: 'Leh', country: 'India', name: 'Kushok Bakula Rimpochee' },
    { code: 'ATQ', city: 'Amritsar', country: 'India', name: 'Sri Guru Ram Dass Jee' },
    { code: 'LUH', city: 'Ludhiana', country: 'India', name: 'Sahnewal' },
    { code: 'IXC', city: 'Chandigarh', country: 'India', name: 'Chandigarh' },
    { code: 'DED', city: 'Dehradun', country: 'India', name: 'Jolly Grant' },
    { code: 'HDO', city: 'Haldwani', country: 'India', name: 'Pantnagar' },
    { code: 'PBC', city: 'Phuntsholing', country: 'Bhutan', name: 'Gelephu' },
    { code: 'PBH', city: 'Paro', country: 'Bhutan', name: 'Paro Intl' },
    { code: 'KTM', city: 'Kathmandu', country: 'Nepal', name: 'Tribhuvan' },
    { code: 'PKR', city: 'Pokhara', country: 'Nepal', name: 'Pokhara' },
    { code: 'BWA', city: 'Bhairahawa', country: 'Nepal', name: 'Gautam Buddha' },
    { code: 'BDP', city: 'Bhadrapur', country: 'Nepal', name: 'Bhadrapur' },
    { code: 'DHI', city: 'Dhangadhi', country: 'Nepal', name: 'Dhangadhi' },
    { code: 'BIR', city: 'Biratnagar', country: 'Nepal', name: 'Biratnagar' },
    { code: 'KEP', city: 'Nepalganj', country: 'Nepal', name: 'Nepalganj' },
    { code: 'BIT', city: 'Baitadi', country: 'Nepal', name: 'Baitadi' },
    { code: 'DOP', city: 'Dolpa', country: 'Nepal', name: 'Dolpa' },
    { code: 'JUM', city: 'Jumla', country: 'Nepal', name: 'Jumla' },
    { code: 'LUA', city: 'Lukla', country: 'Nepal', name: 'Tenzing-Hillary' },
    { code: 'MEY', city: 'Meghauli', country: 'Nepal', name: 'Meghauli' },
    { code: 'NPJ', city: 'Nepalganj', country: 'Nepal', name: 'Nepalganj' },
    { code: 'RJA', city: 'Rajahmundry', country: 'India', name: 'Rajahmundry' },
    { code: 'RJI', city: 'Rajouri', country: 'India', name: 'Rajouri' },
    { code: 'SAG', city: 'Sagar', country: 'India', name: 'Sagar' },
    { code: 'SSE', city: 'Solapur', country: 'India', name: 'Solapur' },
    { code: 'TNI', city: 'Satna', country: 'India', name: 'Satna' },
    { code: 'WGC', city: 'Warangal', country: 'India', name: 'Warangal' },
    { code: 'IXP', city: 'Pathankot', country: 'India', name: 'Pathankot' },
    { code: 'IXU', city: 'Aurangabad', country: 'India', name: 'Aurangabad' },
    { code: 'NDC', city: 'Nanded', country: 'India', name: 'Nanded' },
    { code: 'SNS', city: 'Sindhudurg', country: 'India', name: 'Sindhudurg' },
    { code: 'KLH', city: 'Kolhapur', country: 'India', name: 'Kolhapur' },
    { code: 'KTU', city: 'Kota', country: 'India', name: 'Kota' },
    { code: 'HDO', city: 'Haldwani', country: 'India', name: 'Pantnagar' },
    { code: 'NNS', city: 'Naini Saini', country: 'India', name: 'Naini Saini' },
    { code: 'PGH', city: 'Pantnagar', country: 'India', name: 'Pantnagar' },
    { code: 'QIA', city: 'Charba', country: 'India', name: 'Charba' },
    { code: 'XRY', city: 'Diu', country: 'India', name: 'Diu' },
    { code: 'GOX', city: 'Mopa', country: 'India', name: 'Mopa' },
    { code: 'NMB', city: 'Daman', country: 'India', name: 'Daman' },
    { code: 'STV', city: 'Surat', country: 'India', name: 'Surat' },
    { code: 'BDQ', city: 'Vadodara', country: 'India', name: 'Vadodara' },
    { code: 'RJT', city: 'Rajkot', country: 'India', name: 'Rajkot' },
    { code: 'BHJ', city: 'Bhuj', country: 'India', name: 'Bhuj' },
    { code: 'IXK', city: 'Keshod', country: 'India', name: 'Keshod' },
    { code: 'PBD', city: 'Porbandar', country: 'India', name: 'Porbandar' },
    { code: 'JGA', city: 'Jamnagar', country: 'India', name: 'Jamnagar' },
    { code: 'HSS', city: 'Hissar', country: 'India', name: 'Hissar' },
    { code: 'KNU', city: 'Kanpur', country: 'India', name: 'Kanpur' },
    { code: 'AAGR', city: 'Agra', country: 'India', name: 'Agra' },
    { code: 'VNS', city: 'Varanasi', country: 'India', name: 'Lal Bahadur Shastri' },
    { code: 'GAY', city: 'Gaya', country: 'India', name: 'Gaya' },
    { code: 'DHR', city: 'Darbhanga', country: 'India', name: 'Darbhanga' },
    { code: 'DBR', city: 'Darbhanga', country: 'India', name: 'Darbhanga' },
    { code: 'PUS', city: 'Busan', country: 'South Korea', name: 'Gimhae' },
    // Asia - Central Asia
    { code: 'TAS', city: 'Tashkent', country: 'Uzbekistan', name: 'Islam Karimov' },
    { code: 'ALA', city: 'Almaty', country: 'Kazakhstan', name: 'Almaty Intl' },
    { code: 'NQZ', city: 'Nur-Sultan', country: 'Kazakhstan', name: 'Nursultan Nazarbayev' },
    { code: 'GYD', city: 'Baku', country: 'Azerbaijan', name: 'Heydar Aliyev' },
    { code: 'EVN', city: 'Yerevan', country: 'Armenia', name: 'Zvartnots' },
    { code: 'TBS', city: 'Tbilisi', country: 'Georgia', name: 'Tbilisi Intl' },
    { code: 'KUT', city: 'Kutaisi', country: 'Georgia', name: 'Kutaisi' },
    // Oceania
    { code: 'SYD', city: 'Sydney', country: 'Australia', name: 'Kingsford Smith' },
    { code: 'MEL', city: 'Melbourne', country: 'Australia', name: 'Tullamarine' },
    { code: 'BNE', city: 'Brisbane', country: 'Australia', name: 'Brisbane' },
    { code: 'PER', city: 'Perth', country: 'Australia', name: 'Perth' },
    { code: 'ADL', city: 'Adelaide', country: 'Australia', name: 'Adelaide' },
    { code: 'CBR', city: 'Canberra', country: 'Australia', name: 'Canberra' },
    { code: 'OOL', city: 'Gold Coast', country: 'Australia', name: 'Gold Coast' },
    { code: 'CNS', city: 'Cairns', country: 'Australia', name: 'Cairns' },
    { code: 'TSV', city: 'Townsville', country: 'Australia', name: 'Townsville' },
    { code: 'DRW', city: 'Darwin', country: 'Australia', name: 'Darwin' },
    { code: 'HBA', city: 'Hobart', country: 'Australia', name: 'Hobart' },
    { code: 'CFS', city: 'Coffs Harbour', country: 'Australia', name: 'Coffs Harbour' },
    { code: 'NTL', city: 'Newcastle', country: 'Australia', name: 'Newcastle' },
    { code: 'BNK', city: 'Ballina', country: 'Australia', name: 'Ballina' },
    { code: 'TMW', city: 'Tamworth', country: 'Australia', name: 'Tamworth' },
    { code: 'GLT', city: 'Gladstone', country: 'Australia', name: 'Gladstone' },
    { code: 'BDB', city: 'Bundaberg', country: 'Australia', name: 'Bundaberg' },
    { code: 'MCY', city: 'Sunshine Coast', country: 'Australia', name: 'Sunshine Coast' },
    { code: 'PPP', city: 'Proserpine', country: 'Australia', name: 'Proserpine' },
    { code: 'HTI', city: 'Hamilton Island', country: 'Australia', name: 'Hamilton Island' },
    { code: 'MKY', city: 'Mackay', country: 'Australia', name: 'Mackay' },
    { code: 'ROK', city: 'Rockhampton', country: 'Australia', name: 'Rockhampton' },
    { code: 'BDG', city: 'Bundaberg', country: 'Australia', name: 'Bundaberg' },
    { code: 'LRE', city: 'Longreach', country: 'Australia', name: 'Longreach' },
    { code: 'ISA', city: 'Mount Isa', country: 'Australia', name: 'Mount Isa' },
    { code: 'WEI', city: 'Weipa', country: 'Australia', name: 'Weipa' },
    { code: 'CNS', city: 'Cairns', country: 'Australia', name: 'Cairns' },
    { code: 'TWB', city: 'Toowoomba', country: 'Australia', name: 'Toowoomba Wellcamp' },
    { code: 'ARM', city: 'Armidale', country: 'Australia', name: 'Armidale' },
    { code: 'DBO', city: 'Dubbo', country: 'Australia', name: 'Dubbo' },
    { code: 'LDH', city: 'Lord Howe Island', country: 'Australia', name: 'Lord Howe Island' },
    { code: 'PQQ', city: 'Port Macquarie', country: 'Australia', name: 'Port Macquarie' },
    { code: 'OAG', city: 'Orange', country: 'Australia', name: 'Orange' },
    { code: 'GFF', city: 'Griffith', country: 'Australia', name: 'Griffith' },
    { code: 'WGA', city: 'Wagga Wagga', country: 'Australia', name: 'Wagga Wagga' },
    { code: 'CJD', city: 'Condobolin', country: 'Australia', name: 'Condobolin' },
    { code: 'CNJ', city: 'Cloncurry', country: 'Australia', name: 'Cloncurry' },
    { code: 'OOM', city: 'Cooma', country: 'Australia', name: 'Cooma' },
    { code: 'CWW', city: 'Corowa', country: 'Australia', name: 'Corowa' },
    { code: 'DEN', city: 'Deniliquin', country: 'Australia', name: 'Deniliquin' },
    { code: 'FRS', city: 'Forbes', country: 'Australia', name: 'Forbes' },
    { code: 'GLG', city: 'Glen Innes', country: 'Australia', name: 'Glen Innes' },
    { code: 'GTE', city: 'Groote Eylandt', country: 'Australia', name: 'Groote Eylandt' },
    { code: 'GUL', city: 'Goulburn', country: 'Australia', name: 'Goulburn' },
    { code: 'HXX', city: 'Hay', country: 'Australia', name: 'Hay' },
    { code: 'HOK', city: 'Hook Island', country: 'Australia', name: 'Hook Island' },
    { code: 'KBY', city: 'King Island', country: 'Australia', name: 'King Island' },
    { code: 'KNS', city: 'King Island', country: 'Australia', name: 'King Island' },
    { code: 'KRM', city: 'Karumba', country: 'Australia', name: 'Karumba' },
    { code: 'LSC', city: 'Launceston', country: 'Australia', name: 'Launceston' },
    { code: 'LVO', city: 'Laverton', country: 'Australia', name: 'Laverton' },
    { code: 'MBH', city: 'Maryborough', country: 'Australia', name: 'Maryborough' },
    { code: 'MIM', city: 'Merimbula', country: 'Australia', name: 'Merimbula' },
    { code: 'MNG', city: 'Maningrida', country: 'Australia', name: 'Maningrida' },
    { code: 'MRZ', city: 'Moree', country: 'Australia', name: 'Moree' },
    { code: 'MTQ', city: 'Mitchell', country: 'Australia', name: 'Mitchell' },
    { code: 'NAA', city: 'Narrabri', country: 'Australia', name: 'Narrabri' },
    { code: 'NMP', city: 'Newman', country: 'Australia', name: 'Newman' },
    { code: 'OCT', city: 'Old Crow', country: 'Australia', name: 'Old Crow' },
    { code: 'OLP', city: 'Olympic Dam', country: 'Australia', name: 'Olympic Dam' },
    { code: 'PKE', city: 'Parkes', country: 'Australia', name: 'Parkes' },
    { code: 'PLV', city: 'Phillip Island', country: 'Australia', name: 'Phillip Island' },
    { code: 'PMK', city: 'Palm Island', country: 'Australia', name: 'Palm Island' },
    { code: 'PRD', city: 'Pardoo', country: 'Australia', name: 'Pardoo' },
    { code: 'PUG', city: 'Port Augusta', country: 'Australia', name: 'Port Augusta' },
    { code: 'RMA', city: 'Roma', country: 'Australia', name: 'Roma' },
    { code: 'SHR', city: 'Shark Bay', country: 'Australia', name: 'Shark Bay' },
    { code: 'SLA', city: 'Stampede', country: 'Australia', name: 'Stampede' },
    { code: 'SWH', city: 'Swan Hill', country: 'Australia', name: 'Swan Hill' },
    { code: 'TCA', city: 'Tennant Creek', country: 'Australia', name: 'Tennant Creek' },
    { code: 'TUM', city: 'Tumut', country: 'Australia', name: 'Tumut' },
    { code: 'WYA', city: 'Whyalla', country: 'Australia', name: 'Whyalla' },
    { code: 'WRN', city: 'Warner', country: 'Australia', name: 'Warner' },
    { code: 'WOL', city: 'Wollongong', country: 'Australia', name: 'Wollongong' },
    { code: 'WWY', city: 'West Wyalong', country: 'Australia', name: 'West Wyalong' },
    { code: 'ZNE', city: 'Newman', country: 'Australia', name: 'Newman' },
    { code: 'AKL', city: 'Auckland', country: 'New Zealand', name: 'Auckland' },
    { code: 'WLG', city: 'Wellington', country: 'New Zealand', name: 'Wellington' },
    { code: 'CHC', city: 'Christchurch', country: 'New Zealand', name: 'Christchurch' },
    { code: 'DUD', city: 'Dunedin', country: 'New Zealand', name: 'Dunedin' },
    { code: 'ZQN', city: 'Queenstown', country: 'New Zealand', name: 'Queenstown' },
    { code: 'WRE', city: 'Whangarei', country: 'New Zealand', name: 'Whangarei' },
    { code: 'TRG', city: 'Tauranga', country: 'New Zealand', name: 'Tauranga' },
    { code: 'NPL', city: 'New Plymouth', country: 'New Zealand', name: 'New Plymouth' },
    { code: 'NPE', city: 'Napier', country: 'New Zealand', name: 'Hawke\'s Bay' },
    { code: 'PPQ', city: 'Palmerston North', country: 'New Zealand', name: 'Palmerston North' },
    { code: 'ROT', city: 'Rotorua', country: 'New Zealand', name: 'Rotorua' },
    { code: 'TUO', city: 'Taupo', country: 'New Zealand', name: 'Taupo' },
    { code: 'WHK', city: 'Whakatane', country: 'New Zealand', name: 'Whakatane' },
    { code: 'WSZ', city: 'Westport', country: 'New Zealand', name: 'Westport' },
    { code: 'BHE', city: 'Blenheim', country: 'New Zealand', name: 'Blenheim' },
    { code: 'KBZ', city: 'Kaikoura', country: 'New Zealand', name: 'Kaikoura' },
    { code: 'OHA', city: 'Ohakea', country: 'New Zealand', name: 'Ohakea' },
    { code: 'WAG', city: 'Wanganui', country: 'New Zealand', name: 'Wanganui' },
    { code: 'IVC', city: 'Invercargill', country: 'New Zealand', name: 'Invercargill' },
    { code: 'TIU', city: 'Timaru', country: 'New Zealand', name: 'Timaru' },
    { code: 'MON', city: 'Mount Cook', country: 'New Zealand', name: 'Mount Cook' },
    { code: 'WIR', city: 'Wairoa', country: 'New Zealand', name: 'Wairoa' },
    { code: 'WHO', city: 'Fox Glacier', country: 'New Zealand', name: 'Fox Glacier' },
    { code: 'TEU', city: 'Te Anau', country: 'New Zealand', name: 'Te Anau' },
    { code: 'TUJ', city: 'Tauranga', country: 'New Zealand', name: 'Tauranga' },
    // Pacific Islands
    { code: 'PPT', city: 'Papeete', country: 'French Polynesia', name: "Faa'a" },
    { code: 'NAN', city: 'Nadi', country: 'Fiji', name: 'Nadi Intl' },
    { code: 'SUV', city: 'Suva', country: 'Fiji', name: 'Nausori' },
    { code: 'VLI', city: 'Port Vila', country: 'Vanuatu', name: 'Bauerfield' },
    { code: 'POM', city: 'Port Moresby', country: 'Papua New Guinea', name: 'Jacksons' },
    { code: 'HIR', city: 'Honiara', country: 'Solomon Islands', name: 'Henderson' },
    { code: 'APW', city: 'Apia', country: 'Samoa', name: 'Faleolo' },
    { code: 'TBU', city: "Nuku'alofa", country: 'Tonga', name: "Fua'amotu" },
    { code: 'FUN', city: 'Funafuti', country: 'Tuvalu', name: 'Funafuti Intl' },
    { code: 'MAJ', city: 'Majuro', country: 'Marshall Islands', name: 'Marshall Islands Intl' },
    { code: 'KWA', city: 'Kwajalein', country: 'Marshall Islands', name: 'Bucholz' },
    { code: 'GUM', city: 'Guam', country: 'Guam', name: 'Antonio B. Won Pat' },
    { code: 'SPN', city: 'Saipan', country: 'Northern Mariana Islands', name: 'Saipan Intl' },
    { code: 'ROR', city: 'Koror', country: 'Palau', name: 'Roman Tmetuchl Intl' },
    { code: 'CHC', city: 'Christchurch', country: 'New Zealand', name: 'Christchurch' },
    { code: 'DUD', city: 'Dunedin', country: 'New Zealand', name: 'Dunedin' },
    // Maldives & Sri Lanka
    { code: 'MLE', city: 'Malé', country: 'Maldives', name: 'Velana Intl' },
    { code: 'DRV', city: 'Dharavandhoo', country: 'Maldives', name: 'Dharavandhoo' },
    { code: 'GAN', city: 'Gan', country: 'Maldives', name: 'Gan Intl' },
    { code: 'KDM', city: 'Kadhdhoo', country: 'Maldives', name: 'Kadhdhoo' },
    { code: 'HAQ', city: 'Hanimaadhoo', country: 'Maldives', name: 'Hanimaadhoo Intl' },
    { code: 'CMB', city: 'Colombo', country: 'Sri Lanka', name: 'Bandaranaike' },
    { code: 'RML', city: 'Colombo', country: 'Sri Lanka', name: 'Ratmalana' },
    { code: 'JAF', city: 'Jaffna', country: 'Sri Lanka', name: 'Jaffna Intl' },
    { code: 'TRR', city: 'Trincomalee', country: 'Sri Lanka', name: 'China Bay' },
    { code: 'HRI', city: 'Mattala', country: 'Sri Lanka', name: 'Mattala Rajapaksa' },
    { code: 'GOP', city: 'Galle', country: 'Sri Lanka', name: 'Koggala' },
    { code: 'WRJ', city: 'Walaithithura', country: 'Sri Lanka', name: 'Walalaithithura' },
];

let browserInstance = null;

async function getBrowser() {
    if (!browserInstance || !browserInstance.connected) {
        browserInstance = await puppeteer.launch({
            headless: 'new',
            args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--disable-gpu',
                '--single-process'
            ]
        });
    }
    return browserInstance;
}

async function scrapeGoogleFlights(origin, destination, date) {
    const browser = await getBrowser();
    const page = await browser.newPage();

    try {
        await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36');
        await page.setViewport({ width: 1280, height: 900 });

        const url = `https://www.google.com/travel/flights?q=flights+from+${origin}+to+${destination}+on+${date}`;
        await page.goto(url, { waitUntil: 'networkidle2', timeout: 45000 });

        await new Promise(r => setTimeout(r, 4000));

        const flights = await page.evaluate(() => {
            const results = [];
            const lists = document.querySelectorAll('li');
            lists.forEach(li => {
                const text = li.innerText;
                const priceMatch = text.match(/\$(\d[\d,]*)/);
                if (!priceMatch) return;
                const price = parseInt(priceMatch[1].replace(/,/g, ''));
                if (!price || price < 10 || price > 50000) return;
                const lines = text.split('\n').map(l => l.trim()).filter(Boolean);
                let airline = '';
                let times = '';
                let duration = '';
                let stops = '';
                for (const line of lines) {
                    if (/^\d{1,2}:\d{2}\s*(AM|PM)?\s*[–-]\s*\d{1,2}:\d{2}/.test(line)) {
                        times = line;
                    } else if (/^\d+\s*h\s*\d*\s*m?$/.test(line) || /^\d+h/.test(line)) {
                        duration = line;
                    } else if (/^Nonstop$|^Direct$|^\d+\s*stop/i.test(line)) {
                        stops = line;
                    } else if (line.length > 3 && line.length < 40 && !/^\$/.test(line) && !/^\d/.test(line) && !/stop/i.test(line) && !/h$/.test(line)) {
                        if (!airline) airline = line;
                    }
                }
                if (times || airline) {
                    results.push({ price, airline, times, duration, stops });
                }
            });
            if (results.length === 0) {
                const priceElements = document.querySelectorAll('[data-value]');
                priceElements.forEach(el => {
                    const price = parseInt(el.getAttribute('data-value'));
                    if (price && price > 0 && price < 50000) {
                        results.push({ price, airline: '', times: '', duration: '', stops: '' });
                    }
                });
            }
            return results;
        });

        return flights;
    } catch (err) {
        console.error('Scrape error:', err.message);
        return [];
    } finally {
        await page.close();
    }
}

app.get('/api/airports', (req, res) => {
    const q = (req.query.q || '').toLowerCase();
    if (!q || q.length < 1) return res.json([]);

    const results = airports.filter(a =>
        a.code.toLowerCase().includes(q) ||
        a.city.toLowerCase().includes(q) ||
        a.name.toLowerCase().includes(q) ||
        a.country.toLowerCase().includes(q)
    ).slice(0, 8);

    res.json(results);
});

app.post('/api/search', async (req, res) => {
    const { origin, destination, date } = req.body;
    if (!origin || !destination || !date) {
        return res.status(400).json({ error: 'Missing required fields' });
    }
    try {
        const flights = await scrapeGoogleFlights(origin, destination, date);
        if (flights.length === 0) {
            return res.json({ flights: [], cheapest: null, average: null, total: 0 });
        }
        const sorted = [...flights].sort((a, b) => a.price - b.price);
        const cheapest = sorted[0].price;
        const average = Math.round(sorted.reduce((sum, f) => sum + f.price, 0) / sorted.length);
        res.json({ flights: sorted.slice(0, 20), cheapest, average, total: sorted.length });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

app.get('/api/health', (req, res) => {
    res.json({ status: 'ok' });
});

process.on('SIGTERM', async () => {
    if (browserInstance) await browserInstance.close();
    process.exit(0);
});

app.listen(PORT, () => {
    console.log(`Flight tracker server running on port ${PORT}`);
});
